// Code generated by scripts/sync-sops.py from github.com/getsops/sops/v3
// v3.13.3 (stores/dotenv/store.go, stores/stores.go). DO NOT EDIT.
//
// Licensed under the Mozilla Public License 2.0, like SOPS itself.

package sopscore

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"
	"time"
)

// DotenvStore handles storage of dotenv data
type DotenvStore struct{}

// LoadPlainFile returns the contents of a plaintext file loaded onto a
// sops runtime object
func (store *DotenvStore) LoadPlainFile(in []byte) (TreeBranches, error) {
	var branches TreeBranches
	var branch TreeBranch

	for _, line := range bytes.Split(in, []byte("\n")) {
		if len(line) == 0 {
			continue
		}
		if line[0] == '#' {
			branch = append(branch, TreeItem{
				Key:   Comment{Value: string(line[1:])},
				Value: nil,
			})
		} else {
			pos := bytes.Index(line, []byte("="))
			if pos == -1 {
				return nil, fmt.Errorf("invalid dotenv input line: %s", line)
			}
			branch = append(branch, TreeItem{
				Key:   string(line[:pos]),
				Value: strings.Replace(string(line[pos+1:]), "\\n", "\n", -1),
			})
		}
	}

	branches = append(branches, branch)
	return branches, nil
}

// EmitPlainFile returns the plaintext file's bytes corresponding to a sops
// runtime object
func (store *DotenvStore) EmitPlainFile(in TreeBranches) ([]byte, error) {
	buffer := bytes.Buffer{}
	for _, item := range in[0] {
		if IsComplexValue(item.Value) {
			return nil, fmt.Errorf("cannot use complex value in dotenv file; offending key %s", item.Key)
		}
		var line string
		if comment, ok := item.Key.(Comment); ok {
			line = fmt.Sprintf("#%s\n", comment.Value)
		} else {
			value, ok := item.Value.(string)
			if !ok {
				value = ValToString(item.Value)
			} else {
				value = strings.ReplaceAll(value, "\n", "\\n")
			}

			line = fmt.Sprintf("%s=%s\n", item.Key, value)
		}
		buffer.WriteString(line)
	}
	return buffer.Bytes(), nil
}

// IsComplexValue returns true if the given value is an array or dictionary/hash.
func IsComplexValue(v interface{}) bool {
	switch v.(type) {
	case []interface{}:
		return true
	case TreeBranch:
		return true
	}
	return false
}

// ValToString converts a simple value to a string.
// It does not handle complex values (arrays and mappings).
func ValToString(v interface{}) string {
	switch v := v.(type) {
	case float64:
		result := strconv.FormatFloat(v, 'G', -1, 64)
		// If the result can be confused with an integer, make sure we have at least one decimal digit
		if !strings.ContainsRune(result, '.') && !strings.ContainsRune(result, 'E') {
			result = strconv.FormatFloat(v, 'f', 1, 64)
		}
		return result
	case bool:
		return strconv.FormatBool(v)
	case time.Time:
		return v.Format(time.RFC3339)
	case fmt.Stringer:
		return v.String()
	default:
		return fmt.Sprintf("%v", v)
	}
}
