// Code generated by scripts/sync-sops.py from github.com/getsops/sops/v3
// v3.13.3 (stores/flatten.go). DO NOT EDIT.
//
// Licensed under the Mozilla Public License 2.0, like SOPS itself.

package sopscore

import (
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"
)

const mapSeparator = "__map_"
const listSeparator = "__list_"

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Unflatten

type token interface{}

type mapToken struct {
	key string
}

type listToken struct {
	position int
}

// tokenize converts a path generated by Flatten to be used as a key
// in the flattened map, and converts it to a slice of tokens
func tokenize(path string) []token {
	const (
		StateNormal = 0
		StateMap    = iota
		StateList   = iota
	)
	var tokens []token
	state := StateNormal
	lastTokenEnd := 0
	i := 0
	finishPrevToken := func() {
		var t token
		switch state {
		case StateNormal:
			t = mapToken{path[lastTokenEnd:i]}
		case StateMap:
			t = mapToken{path[lastTokenEnd+len(mapSeparator) : i]}
		case StateList:
			pos, _ := strconv.Atoi(path[lastTokenEnd+len(listSeparator) : i])
			t = listToken{pos}
		}
		lastTokenEnd = i
		tokens = append(tokens, t)
	}
	for i < len(path) {
		if strings.HasPrefix(path[i:], mapSeparator) {
			finishPrevToken()
			state = StateMap
			i += len(mapSeparator)
		} else if strings.HasPrefix(path[i:], listSeparator) {
			finishPrevToken()
			state = StateList
			i += len(listSeparator)
		} else {
			i++
		}
	}
	finishPrevToken()
	return tokens
}

type node struct {
	value   *interface{}
	subkeys map[string]*node
	indices map[int]*node
}

func place(value *interface{}, path []token, root *node) error {
	for _, token := range path {
		var next *node
		var ok bool
		switch t := token.(type) {
		case mapToken:
			if root.subkeys == nil {
				root.subkeys = make(map[string]*node)
			}
			next, ok = root.subkeys[t.key]
			if !ok {
				next = &node{}
				root.subkeys[t.key] = next
			}
		case listToken:
			if root.indices == nil {
				root.indices = make(map[int]*node)
			}
			next, ok = root.indices[t.position]
			if !ok {
				next = &node{}
				root.indices[t.position] = next
			}
		}
		root = next
	}
	if root.value != nil {
		return fmt.Errorf("Duplicate value")
	}
	root.value = value
	return nil
}

func b2i(value bool) int {
	if value {
		return 1
	}
	return 0
}

func convert(root *node) (interface{}, error) {
	hasValue := root.value != nil
	hasSubkey := len(root.subkeys) > 0
	hasIndex := len(root.indices) > 0
	if b2i(hasValue)+b2i(hasSubkey)+b2i(hasIndex) > 1 {
		return nil, fmt.Errorf("Type mismatch")
	}
	if !hasValue && !hasSubkey && !hasIndex {
		return TreeBranch{}, nil
	}
	if hasValue {
		return *root.value, nil
	}
	if hasSubkey {
		keys := make([]string, len(root.subkeys))
		index := 0
		for k := range root.subkeys {
			keys[index] = k
			index += 1
		}
		sort.Strings(keys)
		result := make(TreeBranch, len(keys))
		for index, key := range keys {
			value, err := convert(root.subkeys[key])
			if err != nil {
				return nil, err
			}
			result[index] = TreeItem{
				Key:   key,
				Value: value,
			}
		}
		return result, nil
	}
	minValue := math.MaxInt
	maxValue := math.MinInt
	for k := range root.indices {
		if k < minValue {
			minValue = k
		}
		if k > maxValue {
			maxValue = k
		}
	}
	if minValue != 0 || maxValue+1 != len(root.indices) {
		return nil, fmt.Errorf("Incomplete list")
	}
	result := make([]interface{}, maxValue+1)
	for k, v := range root.indices {
		value, err := convert(v)
		if err != nil {
			return nil, err
		}
		result[k] = value
	}
	return result, nil
}

func unflattenTreeBranch(branch TreeBranch) (TreeBranch, error) {
	root := &node{}
	for _, item := range branch {
		if _, ok := item.Key.(Comment); ok {
			continue
		}
		if key, ok := item.Key.(string); ok {
			tokens := tokenize(key)
			err := place(&item.Value, tokens, root)
			if err != nil {
				return nil, fmt.Errorf("Error while unflattening %q: %w", key, err)
			}
		} else {
			return nil, fmt.Errorf("Found non-string key %q when unflattening", item.Key)
		}
	}
	result, err := convert(root)
	if err != nil {
		return nil, fmt.Errorf("Error while unflattening: %w", err)
	}
	if tb, ok := result.(TreeBranch); ok {
		return tb, nil
	}
	return nil, fmt.Errorf("Internal error: cannot find root")
}
