#!/usr/bin/env python3
"""Regenerates wasm/sopscore/*_sops.go from a SOPS source checkout.

The editor runs SOPS's own Go code for the file format. Importing the SOPS
module would pull in every cloud key service (a ~60 MB WebAssembly file), so
the relevant functions are copied verbatim instead, with only package paths,
logging and audit calls adjusted.

Usage: scripts/sync-sops.py <path to sops checkout> <version tag>
"""
import pathlib
import subprocess
import re
import sys

src = pathlib.Path(sys.argv[1])
version = sys.argv[2]
out = pathlib.Path(__file__).resolve().parent.parent / "wasm" / "sopscore"


def read(rel):
    return (src / rel).read_text()


def decl(text, start):
    """Returns the top-level declaration beginning with `start`, including
    its doc comment, up to the closing brace at column 0."""
    lines = text.split("\n")
    idx = next(i for i, l in enumerate(lines) if l.startswith(start))
    first = idx
    while first > 0 and lines[first - 1].startswith("//"):
        first -= 1
    if lines[idx].endswith("}") or not lines[idx].rstrip().endswith("{"):
        return "\n".join(lines[first : idx + 1]) + "\n"
    end = next(i for i in range(idx + 1, len(lines)) if lines[i] == "}")
    return "\n".join(lines[first : end + 1]) + "\n"


def header(files):
    return (
        "// Code generated by scripts/sync-sops.py from github.com/getsops/sops/v3\n"
        f"// {version} ({', '.join(files)}). DO NOT EDIT.\n"
        "//\n"
        "// Licensed under the Mozilla Public License 2.0, like SOPS itself.\n\n"
        "package sopscore\n\n"
    )


def strip_logging(code):
    code = re.sub(r"\taudit\.SubmitEvent\(.*?\n\t\}\)\n", "", code, flags=re.S)
    code = re.sub(r"\n\t*log\.Debug\([^\n]*\)", "", code)
    code = re.sub(
        r"(\n\t*)log\.WithField\([^\n]*\)\.\s*\n\s*Warn\((?:[^()]|\([^()]*\))*\)",
        r"\1// (SOPS logs a warning here.)",
        code,
        flags=re.S,
    )
    assert "log." not in code and "audit." not in code, "unhandled logging call"
    return code


def write(name, content):
    (out / name).write_text(content)
    print("wrote", out / name)


# --- tree walking, encryption rules, MAC (sops.go) ---
sops_go = read("sops.go")
tree = header(["sops.go"])
tree += 'import (\n\t"crypto/sha512"\n\t"fmt"\n\t"regexp"\n\t"strconv"\n\t"strings"\n\t"time"\n)\n\n'
tree += decl(sops_go, "const DefaultUnencryptedSuffix") + "\n"
tree += decl(sops_go, "var MACOnlyEncryptedInitialization") + "\n"
tree += decl(sops_go, "type Cipher interface").replace("type Cipher interface", "type ValueCipher interface") + "\n"
for start in ["type Comment struct", "type TreeItem struct", "type TreeBranch ", "type TreeBranches "]:
    tree += decl(sops_go, start) + "\n"
for start in [
    "func (branch TreeBranch) walkValue(",
    "func (branch TreeBranch) walkSlice(",
    "func (branch TreeBranch) walkBranch(",
    "func (tree Tree) shouldBeEncrypted(",
    "func (tree Tree) Encrypt(",
    "func (tree Tree) Decrypt(",
    "func ToBytes(",
]:
    tree += strip_logging(decl(sops_go, start)).replace("cipher Cipher)", "cipher ValueCipher)") + "\n"
write("tree_sops.go", tree)

# --- AES-GCM value cipher (aes/cipher.go) ---
aes = read("aes/cipher.go")
aes = aes[aes.index("import (") :]
aes = re.sub(r'\n\t"github.com/getsops/sops/v3"\n\t"github.com/getsops/sops/v3/logging"\n\t"github.com/sirupsen/logrus"\n', "\n", aes)
aes = re.sub(r"var log \*logrus\.Logger\n\nfunc init\(\) \{\n\tlog = logging\.NewLogger\(\"AES\"\)\n\}\n\n", "", aes)
aes = aes.replace("sops.Comment", "Comment")
write("aes_sops.go", header(["aes/cipher.go"]) + strip_logging(aes))

# --- YAML store (stores/yaml/store.go) ---
yml = read("stores/yaml/store.go")
body = yml[yml.index("func (store Store) appendCommentToList(") : yml.index("// LoadEncryptedFile")]
body += decl(yml, "func (store *Store) LoadPlainFile(")
emit = decl(yml, "func (store *Store) EmitPlainFile(")
emit = emit.replace(
    "\tindent, err := store.getIndentation()\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\te.SetIndent(indent)",
    "\te.SetIndent(IndentDefault)",
)
assert "getIndentation" not in emit
body += emit
body = body.replace("sops.", "").replace("(store Store)", "(store YAMLStore)").replace("(store *Store)", "(store *YAMLStore)")
yml_out = header(["stores/yaml/store.go"])
yml_out += 'import (\n\t"bytes"\n\t"fmt"\n\t"io"\n\t"strings"\n\n\t"go.yaml.in/yaml/v3"\n)\n\n'
yml_out += "const IndentDefault = 4\n\n// YAMLStore handles storage of YAML data\ntype YAMLStore struct{}\n\n" + body
write("yamlstore_sops.go", yml_out)

# --- dotenv store (stores/dotenv/store.go) and helpers from stores/stores.go ---
env = read("stores/dotenv/store.go")
stores_go = read("stores/stores.go")
body = decl(env, "func (store *Store) LoadPlainFile(") + "\n" + decl(env, "func (store *Store) EmitPlainFile(") + "\n"
body += decl(stores_go, "func IsComplexValue(") + "\n" + decl(stores_go, "func ValToString(")
body = body.replace("stores.", "").replace("sops.", "").replace("(store *Store)", "(store *DotenvStore)")
env_out = header(["stores/dotenv/store.go", "stores/stores.go"])
env_out += 'import (\n\t"bytes"\n\t"fmt"\n\t"strconv"\n\t"strings"\n\t"time"\n)\n\n'
env_out += "// DotenvStore handles storage of dotenv data\ntype DotenvStore struct{}\n\n" + body
write("dotenvstore_sops.go", env_out)

# --- unflattening of dotenv metadata keys (stores/flatten.go) ---
flat = read("stores/flatten.go")
body = flat[flat.index("const mapSeparator") : flat.index("////////", flat.index("func unflattenTreeBranch("))]
body = body.replace("sops.", "")
flat_out = header(["stores/flatten.go"])
flat_out += 'import (\n\t"fmt"\n\t"math"\n\t"sort"\n\t"strconv"\n\t"strings"\n)\n\n' + body.rstrip() + "\n"
write("flatten_sops.go", flat_out)

subprocess.run(["gofmt", "-w"] + [str(p) for p in out.glob("*_sops.go")], check=True)
